before_script:
  - docker info
  - docker-compose --version

build images:
  stage: build
  script:
    - cd docker && cp .env.example .env
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml build

test up:
  stage: test
  script:
    - cd docker && cp .env.example .env
    - docker-compose -f docker-compose.yml up -d
